export declare const SUPPORTED_ARCHES: string[];
export declare const VERSION = "v4.31.0";
export declare const DIGESTS: {
    "dragonfly-64": string;
    "freebsd-32": string;
    "freebsd-64": string;
    "linux-32": string;
    "linux-64": string;
    "linux-arm32-v5": string;
    "linux-arm32-v6": string;
    "linux-arm32-v7a": string;
    "linux-arm64-v8a": string;
    "linux-mips32": string;
    "linux-mips32le": string;
    "linux-mips64": string;
    "linux-mips64le": string;
    "linux-ppc64": string;
    "linux-ppc64le": string;
    "linux-riscv64": string;
    "linux-s390x": string;
    "macos-64": string;
    "openbsd-32": string;
    "openbsd-64": string;
    "windows-32": string;
    "windows-64": string;
    "windows-arm32-v7a": string;
};
export declare const fetchDigest: (arch: any) => Promise<any>;
export declare const fetchAllDigests: () => Promise<{}>;
export declare const printDigestJSON: () => Promise<void>;
export declare const getDigestHex: (arch: any, hashType: any) => any;
export declare const HANDLE_DIRECTORY: string;
export declare const PROGRAM_FILEPATH: string;
export declare const detectArch: () => string;
export declare const fetchAndVerifyRelease: (hashType?: string) => Promise<void>;
export declare const checkIfExists: () => Promise<any>;
export declare const v2ray: (config: any) => Promise<unknown>;
